---
version: '3'
services:
    zookeeper-1:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper1
        container_name: zookeeper1
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: "2181"
            ZOOKEEPER_TICK_TIME: "2000"
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888;zookeeper6:2888:3888
            ZOOKEEPER_GROUPS: 1:2:3;4:5:6
        ports:
            - "2181:2181"
    zookeeper-2:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper2
        container_name: zookeeper2
        environment:
            ZOOKEEPER_SERVER_ID: 2
            ZOOKEEPER_CLIENT_PORT: "2181"
            ZOOKEEPER_TICK_TIME: "2000"
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888;zookeeper6:2888:3888
            ZOOKEEPER_GROUPS: 1:2:3;4:5:6
        ports:
            - "2182:2181"
    zookeeper-3:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper3
        container_name: zookeeper3
        environment:
            ZOOKEEPER_SERVER_ID: 3
            ZOOKEEPER_CLIENT_PORT: "2181"
            ZOOKEEPER_TICK_TIME: "2000"
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888;zookeeper6:2888:3888
            ZOOKEEPER_GROUPS: 1:2:3;4:5:6
        ports:
            - "2183:2181"
    zookeeper-4:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper4
        container_name: zookeeper4
        environment:
            ZOOKEEPER_SERVER_ID: 4
            ZOOKEEPER_CLIENT_PORT: "2181"
            ZOOKEEPER_TICK_TIME: "2000"
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888;zookeeper6:2888:3888
            ZOOKEEPER_GROUPS: 1:2:3;4:5:6
        ports:
            - "2184:2181"
    zookeeper-5:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper5
        container_name: zookeeper5
        environment:
            ZOOKEEPER_SERVER_ID: 5
            ZOOKEEPER_CLIENT_PORT: "2181"
            ZOOKEEPER_TICK_TIME: "2000"
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888;zookeeper6:2888:3888
            ZOOKEEPER_GROUPS: 1:2:3;4:5:6
        ports:
            - "2185:2181"
    zookeeper-6:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper6
        container_name: zookeeper6
        environment:
            ZOOKEEPER_SERVER_ID: 6
            ZOOKEEPER_CLIENT_PORT: "2181"
            ZOOKEEPER_TICK_TIME: "2000"
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888;zookeeper6:2888:3888
            ZOOKEEPER_GROUPS: 1:2:3;4:5:6
        ports:
            - "2186:2181"

